// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWRkhElpBhQLRtMyBv-vtH3T1khp_Cyj0',
    appId: '1:161455724595:web:bf26aba69a9df9474d6b46',
    messagingSenderId: '161455724595',
    projectId: 'triptales-c73ce',
    authDomain: 'triptales-c73ce.firebaseapp.com',
    storageBucket: 'triptales-c73ce.firebasestorage.app',
    measurementId: 'G-Q87GSB5JYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7ib9K41i_9uuGOt8tymW8g0CwM5KIYc',
    appId: '1:161455724595:android:a9238d074020cad64d6b46',
    messagingSenderId: '161455724595',
    projectId: 'triptales-c73ce',
    storageBucket: 'triptales-c73ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV7KoD5SJLmVAdZpjuesssnRpDziUHthg',
    appId: '1:161455724595:ios:057ecab314dd85424d6b46',
    messagingSenderId: '161455724595',
    projectId: 'triptales-c73ce',
    storageBucket: 'triptales-c73ce.firebasestorage.app',
    iosBundleId: 'com.example.triptale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV7KoD5SJLmVAdZpjuesssnRpDziUHthg',
    appId: '1:161455724595:ios:057ecab314dd85424d6b46',
    messagingSenderId: '161455724595',
    projectId: 'triptales-c73ce',
    storageBucket: 'triptales-c73ce.firebasestorage.app',
    iosBundleId: 'com.example.triptale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWRkhElpBhQLRtMyBv-vtH3T1khp_Cyj0',
    appId: '1:161455724595:web:1bc84e167e10e6324d6b46',
    messagingSenderId: '161455724595',
    projectId: 'triptales-c73ce',
    authDomain: 'triptales-c73ce.firebaseapp.com',
    storageBucket: 'triptales-c73ce.firebasestorage.app',
    measurementId: 'G-LHH88WFDWM',
  );
}
